# Generated by Django 3.0.1 on 2019-12-30 02:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier.', unique=True, verbose_name='Unique Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation Date.', verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last Update.', verbose_name='Date Updated')),
                ('document', models.CharField(max_length=15)),
                ('documentType', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier.', unique=True, verbose_name='Unique Identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation Date.', verbose_name='Date Created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last Update.', verbose_name='Date Updated')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('PAYED', 'PAYED'), ('REJECTED', 'REJECTED')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
