# Generated by Django 3.0.1 on 2019-12-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='documentType',
            field=models.CharField(choices=[('CC', 'CC'), ('CE', 'CE')], max_length=2),
        ),
    ]
